### ISSUE TITLE
SimpLESS Stopped Generating CSS

### ISSUE THREAD

**Issue by marcelovcpereira** [Paratron/SimpLESS#136]
My SimpLESS has just stopped regenerating the css file.
It continues to show errors when I intentionally inject them in the less file, but the css file is never outputted. I tried to fix removing the previously generated css from the folder, but although it recognizes the less file was "never compiled", when I remove the error it does not generate the css output.

I'm using SimpLESS 1.4 - less v1.3.0 on Windows 7.

**Comment by JSW888** [comment]
Same exact issue here, same version and OS. Just randomly stopped compiling in the middle of developing. I still get error notifications, but it refuses to recompile.

It doesn't appear that this is app is supported anymore anyway.

**Comment by krismeister** [comment]
It's hard to justify the need for this app any longer, with grunt and gulp being so prevalent.

**Comment by Paratron** [comment]
The issue doesnt apply anymore since a long time. Please use version 2.0 from the 2.0 tree of this repository.
