### ISSUE TITLE
Media query error

### ISSUE THREAD

**Issue by robeno** [Paratron/SimpLESS#142]
Hi,
At first, thanks for great app :-)
I am having error, when I try to compile:
@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) {}

This media query is correct, and it is possible to compile it with different compilers.

**Comment by anirugu** [comment]
Hello @Paratron  Where is the 2.0 version for Windows ?

**Comment by Paratron** [comment]
There are currently no pre-built binaries available. Take a look into the README file of the 2.0 branch ( https://github.com/Paratron/SimpLESS/tree/2.0 ) and see the build steps there. If you already have npm installed on your machine, its an easy progress.
