### ISSUE TITLE
Simpless Error On Mac

### ISSUE THREAD

**Issue by etreby** [Paratron/SimpLESS#145]
Couldn't load file:/Users/etreby/Library/Application Support/Titanium/runtime/osx/1.1.0/libkhost.dylib, error: dlopen(/Users/etreby/Library/Application Support/Titanium/runtime/osx/1.1.0/libkhost.dylib, 9): Symbol not found: __ZN3JSC10JSDataView6s_infoE
  Referenced from: /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/WebCore
  Expected in: /Users/etreby/Library/Application Support/Titanium/runtime/osx/1.1.0/JavaScriptCore.framework/Versions/A/JavaScriptCore
 in /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/WebCore

**Comment by Paratron** [comment]
You are using the old version 1.4 whose framework won't work anymore today. Please try version 2.0 from the according branch here on github.
