### ISSUE TITLE
Not run on Win XP Sp2

### ISSUE THREAD

**Issue by sibputnik** [Paratron/SimpLESS#146]
Hi.

I download latest (1.4-win) version, and can not run it. When I run installer.exe, it fails with: "the installer could not determine the application path". Simpleless.exe fails with error "нет доступа", that can be translatetd as "no access".

What can I do to fix it? No tools for XP sp2 & less, elki-palki.

**Comment by Paratron** [comment]
The latest version of Simpless is 2.0 - please try building the app from [the 2.0 branch](https://github.com/Paratron/SimpLESS/tree/2.0).

If this also does not work, I am afraid I am unable to help you - windows xp is just too old and I don't even have a machine to debug anything on windows XP :(
